# Generated by Django 6.0.3 on 2026-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_payment_status_payment_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name="Ссылка на оплату"),
        ),
    ]
